
// StoryWeaver Complete Languages Module (151+ Languages)
export const STORYWEAVER_LANGUAGES = {
  // All 151 Languages with Native Names
  'Acholi': 'Acholi',
  'Afrikaans': 'Afrikaans',
  'Akuapem Twi': 'Akuapem Twi',
  'Albanian': 'Shqiptare',
  'Amharic': 'አማርኛ',
  'Angika': 'अंगिका',
  'Arabic': 'العربية',
  'Armenian': 'Հայերեն',
  'Assamese': 'অসমীয়া',
  'Awadhi': 'अवधी',
  'Bada': 'বাড়া',
  'Badaga': 'বডাগা',
  'Bagheli': 'बघेली',
  'Bagri': 'बागरी',
  'Bahar': 'बाहर',
  'Bahasa Indonesia': 'Bahasa Indonesia',
  'Banjari': 'बंजारी',
  'Basa Sunda': 'Basa Sunda',
  'Basque': 'Euskara',
  'Bengali': 'বাংলা',
  'Bhil': 'भील',
  'Bhojpuri': 'भोजपुरी',
  'Bilingual': 'Bilingual',
  'Bodo': 'বোড়ো',
  'Bundeli': 'बुंदेली',
  'Catalan': 'Català',
  'Cebuano': 'Cebuano',
  'Chhattisgarhi': 'छत्तीसगढ़ी',
  'ChiShona': 'ChiShona',
  'Chinese': '中文',
  'Chinese (Simplified)': '中文(简体)',
  'Chinese (Traditional)': '中文(繁體)',
  'Chocolteco': 'Chocolteco',
  'Chokri': 'चोक्री',
  'Czech': 'Čeština',
  'Dadri': 'दादरी',
  'Danish': 'Dansk',
  'Deori': 'डेरी',
  'Dimasa': 'डिमासा',
  'Dogri': 'डोगरी',
  'Dutch': 'Nederlands',
  'English': 'English',
  'Ewe': 'Ewe',
  'Farsi/Persian': 'فارسی',
  'Filipino': 'Filipino',
  'Finnish': 'Suomi',
  'Gangte': 'गांग्ते',
  'Garo': 'গারো',
  'Garwali': 'गढ़वाली',
  'German': 'Deutsch',
  'Gondi': 'गोंडी',
  'Greek': 'Ελληνικά',
  'Gujarati': 'ગુજરાતી',
  'Gujjari': 'गुज्जरी',
  'Halbi': 'हलबी',
  'Haryanvi': 'हरियाणवी',
  'Hausa': 'Hausa',
  'Hebrew': 'עברית',
  'Himachali': 'हिमाचली',
  'Hindi': 'हिंदी',
  'Ho': 'हो',
  'Hungarian': 'Magyar',
  'Igbo': 'Igbo',
  'Italian': 'Italiano',
  'Kannada': 'ಕನ್ನಡ',
  'Kharia': 'खारिया',
  'Khmer': 'ខ្មែរ',
  'Kinyarwanda': 'Kinyarwanda',
  'Kirundi': 'Kirundi',
  'Kiswahili': 'Kiswahili',
  'Kochila Tharu': 'कोचिला थारु',
  'Kodava': 'कोडव',
  'Kolami': 'कोलामी',
  'Konkani': 'कोंकणी',
  'Kora': 'कोरा',
  'Korean': '한국어',
  'Korku': 'कोरकु',
  'Kumaoni': 'कुमाऊनी',
  'Kurdish': 'کوردی',
  'Kurukh': 'कुरुख',
  'Kuvi': 'कुवी',
  'Kyrgyz': 'Кыргызча',
  'Lambadi': 'लम्बाडी',
  'Lao': 'ລາວ',
  'Latvian': 'Latvian',
  'Lepcha': 'लेप्चा',
  'Lithuanian': 'Lietuvių',
  'Lozi': 'Lozi',
  'Luganda': 'Luganda',
  'Lusoga': 'Lusoga',
  'Luxembourgish': 'Lëtzebuergesch',
  'Macedonian': 'Македонски',
  'Maithili': 'मैथिली',
  'Malay': 'Bahasa Melayu',
  'Malayalam': 'മലയാളം',
  'Manipuri': 'মৈতৈলোল',
  'Marathi': 'मराठी',
  'Meitei': 'Meitei',
  'Mongolian': 'Монгол',
  'Munda': 'मुंडा',
  'Mundari': 'मुंडारी',
  'Nahuatl': 'Nahuatl',
  'Nepali': 'नेपाली',
  'Newari': 'नेवारी',
  'Norwegian': 'Norsk',
  'Odia': 'ଓଡ଼ିଆ',
  'Paite': 'पाइते',
  'Polish': 'Polski',
  'Portuguese': 'Português',
  'Punjabi': 'ਪੰਜਾਬੀ',
  'Rana Tharu': 'राना थारु',
  'Rapa Nui': 'Rapa Nui',
  'Romanian': 'Română',
  'Russian': 'Русский',
  'Sadri': 'सादरी',
  'Sanskrit': 'संस्कृतम्',
  'Santhali': 'ᱥᱟᱱᱛᱟᱲᱤ',
  'Serbian': 'Српски',
  'Serbian (Latin Script)': 'Srpski (Latin)',
  'Sherpa': 'शेर्पा',
  'SiLozi': 'SiLozi',
  'Sindhi': 'سنڌي',
  'Slovak': 'Slovenčina',
  'Slovene': 'Slovenščina',
  'Somali': 'Somali',
  'Spanish': 'Español',
  'Sunda': 'Sunda',
  'Sundanese': 'Bahasa Sunda',
  'Surjapuri': 'सूरजपुरी',
  'Swahili': 'Kiswahili',
  'Swedish': 'Svenska',
  'Tagalog': 'Tagalog',
  'Tamil': 'தமிழ்',
  'Tangkhul': 'তাঙ্খুল',
  'Telugu': 'తెలుగు',
  'Thai': 'ไทย',
  'Tibetan': 'བོད་ཡིག',
  'Tigrinya': 'ትግርኛ',
  'Tiv': 'Tiv',
  'Tulu': 'തുളു',
  'Turkish': 'Türkçe',
  'Turkmen': 'Türkmençe',
  'Ukrainian': 'Українська',
  'Urdu': 'اردو',
  'Uyghur': 'ئۇيغۇرچە',
  'Vietnamese': 'Tiếng Việt',
  'Welsh': 'Cymraeg',
  'Wolof': 'Wolof',
  'Xhosa': 'isiXhosa',
  'Yoruba': 'Yorùbá',
  'Zulu': 'isiZulu',
};

export const STORYWEAVER_LANGUAGES_LIST = [
  'Acholi',
  'Afrikaans',
  'Akuapem Twi',
  'Albanian',
  'Amharic',
  'Angika',
  'Arabic',
  'Armenian',
  'Assamese',
  'Awadhi',
  'Bada',
  'Badaga',
  'Bagheli',
  'Bagri',
  'Bahar',
  'Bahasa Indonesia',
  'Banjari',
  'Basa Sunda',
  'Basque',
  'Bengali',
  'Bhil',
  'Bhojpuri',
  'Bilingual',
  'Bodo',
  'Bundeli',
  'Catalan',
  'Cebuano',
  'Chhattisgarhi',
  'ChiShona',
  'Chinese',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Chocolteco',
  'Chokri',
  'Czech',
  'Dadri',
  'Danish',
  'Deori',
  'Dimasa',
  'Dogri',
  'Dutch',
  'English',
  'Ewe',
  'Farsi/Persian',
  'Filipino',
  'Finnish',
  'Gangte',
  'Garo',
  'Garwali',
  'German',
  'Gondi',
  'Greek',
  'Gujarati',
  'Gujjari',
  'Halbi',
  'Haryanvi',
  'Hausa',
  'Hebrew',
  'Himachali',
  'Hindi',
  'Ho',
  'Hungarian',
  'Igbo',
  'Italian',
  'Kannada',
  'Kharia',
  'Khmer',
  'Kinyarwanda',
  'Kirundi',
  'Kiswahili',
  'Kochila Tharu',
  'Kodava',
  'Kolami',
  'Konkani',
  'Kora',
  'Korean',
  'Korku',
  'Kumaoni',
  'Kurdish',
  'Kurukh',
  'Kuvi',
  'Kyrgyz',
  'Lambadi',
  'Lao',
  'Latvian',
  'Lepcha',
  'Lithuanian',
  'Lozi',
  'Luganda',
  'Lusoga',
  'Luxembourgish',
  'Macedonian',
  'Maithili',
  'Malay',
  'Malayalam',
  'Manipuri',
  'Marathi',
  'Meitei',
  'Mongolian',
  'Munda',
  'Mundari',
  'Nahuatl',
  'Nepali',
  'Newari',
  'Norwegian',
  'Odia',
  'Paite',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Rana Tharu',
  'Rapa Nui',
  'Romanian',
  'Russian',
  'Sadri',
  'Sanskrit',
  'Santhali',
  'Serbian',
  'Serbian (Latin Script)',
  'Sherpa',
  'SiLozi',
  'Sindhi',
  'Slovak',
  'Slovene',
  'Somali',
  'Spanish',
  'Sunda',
  'Sundanese',
  'Surjapuri',
  'Swahili',
  'Swedish',
  'Tagalog',
  'Tamil',
  'Tangkhul',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tiv',
  'Tulu',
  'Turkish',
  'Turkmen',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Vietnamese',
  'Welsh',
  'Wolof',
  'Xhosa',
  'Yoruba',
  'Zulu',
];

export function mapLanguageToStoryWeaver(language: string): string | null {
  const normalized = language.toLowerCase().trim();

  const languageMap: Record<string, string> = {
    'acholi': 'Acholi',
    'afrikaans': 'Afrikaans',
    'akuapem twi': 'Akuapem Twi',
    'albanian': 'Albanian',
    'shqiptare': 'Albanian',
    'amharic': 'Amharic',
    'አማርኛ': 'Amharic',
    'angika': 'Angika',
    'arabic': 'Arabic',
    'العربية': 'Arabic',
    'armenian': 'Armenian',
    'հայերեն': 'Armenian',
    'assamese': 'Assamese',
    'assami': 'Assamese',
    'awadhi': 'Awadhi',
    'bada': 'Bada',
    'badaga': 'Badaga',
    'bagheli': 'Bagheli',
    'bagri': 'Bagri',
    'bahar': 'Bahar',
    'bahasa indonesia': 'Bahasa Indonesia',
    'indonesian': 'Bahasa Indonesia',
    'banjari': 'Banjari',
    'basa sunda': 'Basa Sunda',
    'sundanese': 'Sundanese',
    'basque': 'Basque',
    'euskara': 'Basque',
    'bengali': 'Bengali',
    'bhil': 'Bhil',
    'bhojpuri': 'Bhojpuri',
    'bilingual': 'Bilingual',
    'bodo': 'Bodo',
    'bundeli': 'Bundeli',
    'catalan': 'Catalan',
    'català': 'Catalan',
    'cebuano': 'Cebuano',
    'chhattisgarhi': 'Chhattisgarhi',
    'chishona': 'ChiShona',
    'chinese': 'Chinese (Simplified)',
    '中文': 'Chinese (Simplified)',
    'chinese simplified': 'Chinese (Simplified)',
    'chinese traditional': 'Chinese (Traditional)',
    'chocolteco': 'Chocolteco',
    'chokri': 'Chokri',
    'czech': 'Czech',
    'čeština': 'Czech',
    'dadri': 'Dadri',
    'danish': 'Danish',
    'dansk': 'Danish',
    'deori': 'Deori',
    'dimasa': 'Dimasa',
    'dogri': 'Dogri',
    'dutch': 'Dutch',
    'nederlands': 'Dutch',
    'english': 'English',
    'ewe': 'Ewe',
    'farsi': 'Farsi/Persian',
    'persian': 'Farsi/Persian',
    'فارسی': 'Farsi/Persian',
    'filipino': 'Filipino',
    'finnish': 'Finnish',
    'suomi': 'Finnish',
    'gangte': 'Gangte',
    'garo': 'Garo',
    'garwali': 'Garwali',
    'german': 'German',
    'deutsch': 'German',
    'gondi': 'Gondi',
    'greek': 'Greek',
    'ελληνικά': 'Greek',
    'gujarati': 'Gujarati',
    'gujjari': 'Gujjari',
    'halbi': 'Halbi',
    'haryanvi': 'Haryanvi',
    'hausa': 'Hausa',
    'hebrew': 'Hebrew',
    'עברית': 'Hebrew',
    'himachali': 'Himachali',
    'hindi': 'Hindi',
    'हिंदी': 'Hindi',
    'ho': 'Ho',
    'hungarian': 'Hungarian',
    'magyar': 'Hungarian',
    'igbo': 'Igbo',
    'italian': 'Italian',
    'italiano': 'Italian',
    'kannada': 'Kannada',
    'kharia': 'Kharia',
    'khmer': 'Khmer',
    'ខ្មែរ': 'Khmer',
    'kinyarwanda': 'Kinyarwanda',
    'kirundi': 'Kirundi',
    'kiswahili': 'Kiswahili',
    'swahili': 'Kiswahili',
    'kochila tharu': 'Kochila Tharu',
    'kodava': 'Kodava',
    'kolami': 'Kolami',
    'konkani': 'Konkani',
    'kora': 'Kora',
    'korean': 'Korean',
    '한국어': 'Korean',
    'korku': 'Korku',
    'kumaoni': 'Kumaoni',
    'kurdish': 'Kurdish',
    'کوردی': 'Kurdish',
    'kurukh': 'Kurukh',
    'kuvi': 'Kuvi',
    'kyrgyz': 'Kyrgyz',
    'кыргызча': 'Kyrgyz',
    'lambadi': 'Lambadi',
    'lao': 'Lao',
    'ລາວ': 'Lao',
    'latvian': 'Latvian',
    'lepcha': 'Lepcha',
    'lithuanian': 'Lithuanian',
    'lietuvių': 'Lithuanian',
    'lozi': 'Lozi',
    'luganda': 'Luganda',
    'lusoga': 'Lusoga',
    'luxembourgish': 'Luxembourgish',
    'lëtzebuergesch': 'Luxembourgish',
    'macedonian': 'Macedonian',
    'македонски': 'Macedonian',
    'maithili': 'Maithili',
    'malay': 'Malay',
    'bahasa melayu': 'Malay',
    'malayalam': 'Malayalam',
    'manipuri': 'Manipuri',
    'meitei': 'Manipuri',
    'marathi': 'Marathi',
    'mongolian': 'Mongolian',
    'монгол': 'Mongolian',
    'munda': 'Munda',
    'mundari': 'Mundari',
    'nahuatl': 'Nahuatl',
    'nepali': 'Nepali',
    'newari': 'Newari',
    'norwegian': 'Norwegian',
    'norsk': 'Norwegian',
    'odia': 'Odia',
    'oriya': 'Odia',
    'paite': 'Paite',
    'polish': 'Polish',
    'polski': 'Polish',
    'portuguese': 'Portuguese',
    'português': 'Portuguese',
    'punjabi': 'Punjabi',
    'rana tharu': 'Rana Tharu',
    'rapa nui': 'Rapa Nui',
    'romanian': 'Romanian',
    'română': 'Romanian',
    'russian': 'Russian',
    'русский': 'Russian',
    'sadri': 'Sadri',
    'sanskrit': 'Sanskrit',
    'संस्कृतम्': 'Sanskrit',
    'santhali': 'Santhali',
    'santali': 'Santhali',
    'serbian': 'Serbian',
    'srpski': 'Serbian',
    'srpski (latin)': 'Serbian (Latin Script)',
    'sherpa': 'Sherpa',
    'silozi': 'SiLozi',
    'sindhi': 'Sindhi',
    'سنڌي': 'Sindhi',
    'slovak': 'Slovak',
    'slovenčina': 'Slovak',
    'slovene': 'Slovene',
    'slovenščina': 'Slovene',
    'somali': 'Somali',
    'soomaali': 'Somali',
    'spanish': 'Spanish',
    'español': 'Spanish',
    'sunda': 'Sunda',
    'surjapuri': 'Surjapuri',
    'swedish': 'Swedish',
    'svenska': 'Swedish',
    'tagalog': 'Tagalog',
    'tamil': 'Tamil',
    'தமிழ்': 'Tamil',
    'tangkhul': 'Tangkhul',
    'telugu': 'Telugu',
    'తెలుగు': 'Telugu',
    'thai': 'Thai',
    'ไทย': 'Thai',
    'tibetan': 'Tibetan',
    'བོད་ཡིག': 'Tibetan',
    'tigrinya': 'Tigrinya',
    'ትግርኛ': 'Tigrinya',
    'tiv': 'Tiv',
    'tulu': 'Tulu',
    'turkish': 'Turkish',
    'türkçe': 'Turkish',
    'turkmen': 'Turkmen',
    'türkmençe': 'Turkmen',
    'ukrainian': 'Ukrainian',
    'українська': 'Ukrainian',
    'urdu': 'Urdu',
    'اردو': 'Urdu',
    'uyghur': 'Uyghur',
    'ئۇيغۇرچە': 'Uyghur',
    'vietnamese': 'Vietnamese',
    'tiếng việt': 'Vietnamese',
    'welsh': 'Welsh',
    'cymraeg': 'Welsh',
    'wolof': 'Wolof',
    'xhosa': 'Xhosa',
    'isixhosa': 'Xhosa',
    'yoruba': 'Yoruba',
    'yorùbá': 'Yoruba',
    'zulu': 'Zulu',
    'isizulu': 'Zulu',
  };

  if (languageMap[normalized]) {
    return languageMap[normalized];
  }

  for (const [key, value] of Object.entries(languageMap)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return value;
    }
  }

  return null;
}

export function getLanguageNativeName(language: string): string {
  return (
    STORYWEAVER_LANGUAGES[language as keyof typeof STORYWEAVER_LANGUAGES] || language
  );
}

export function isIndianLanguage(language: string): boolean {
  const indianLanguages = [
    'Hindi',
    'Bengali',
    'Tamil',
    'Telugu',
    'Kannada',
    'Malayalam',
    'Marathi',
    'Gujarati',
    'Punjabi',
    'Urdu',
    'Assamese',
    'Odia',
    'Konkani',
    'Nepali',
    'Manipuri',
    'Meitei',
    'Santhali',
    'Sindhi',
    'Kashmiri',
    'Maithili',
    'Bhojpuri',
    'Sanskrit',
    'Dogri',
    'Bodo',
    'Chhattisgarhi',
    'Angika',
    'Awadhi',
    'Garo',
    'Garwali',
    'Gondi',
    'Halbi',
    'Himachali',
    'Ho',
    'Kharia',
    'Kochila Tharu',
    'Kodava',
    'Kolami',
    'Kora',
    'Korku',
    'Kumaoni',
    'Kurukh',
    'Kuvi',
    'Lambadi',
    'Lepcha',
    'Mundari',
    'Munda',
    'Newari',
    'Rana Tharu',
    'Sadri',
    'Sherpa',
    'Surjapuri',
    'Tangkhul',
    'Tibetan',
    'Tulu',
    'Bagheli',
    'Bagri',
    'Bundeli',
    'Deori',
    'Dimasa',
    'Gujjari',
    'Haryanvi',
    'Badaga',
    'Bada',
    'Bahar',
    'Banjari',
    'Bhil',
    'Chokri',
    'Dadri',
  ];
  return indianLanguages.includes(language);
}

export function isAfricanLanguage(language: string): boolean {
  const africanLanguages = [
    'Acholi',
    'Ewe',
    'Hausa',
    'Igbo',
    'Kiswahili',
    'Kinyarwanda',
    'Kirundi',
    'Lozi',
    'Luganda',
    'Lusoga',
    'SiLozi',
    'Somali',
    'Swahili',
    'Tigrinya',
    'Tiv',
    'Wolof',
    'Xhosa',
    'Yoruba',
    'Zulu',
    'Amharic',
    'ChiShona',
    'Akuapem Twi',
  ];
  return africanLanguages.includes(language);
}

export function isSoutheastAsianLanguage(language: string): boolean {
  const seAsianLanguages = [
    'Bahasa Indonesia',
    'Basa Sunda',
    'Sundanese',
    'Khmer',
    'Lao',
    'Thai',
    'Tagalog',
    'Filipino',
  ];
  return seAsianLanguages.includes(language);
}

export function getLanguageRegion(language: string): string {
  if (isIndianLanguage(language)) return 'Indian';
  if (isAfricanLanguage(language)) return 'African';
  if (isSoutheastAsianLanguage(language)) return 'Southeast Asian';

  const europeanLanguages = [
    'English',
    'Spanish',
    'French',
    'German',
    'Portuguese',
    'Italian',
    'Russian',
    'Polish',
    'Dutch',
    'Greek',
    'Swedish',
    'Norwegian',
    'Danish',
    'Finnish',
    'Czech',
    'Hungarian',
    'Romanian',
    'Bulgarian',
    'Croatian',
    'Serbian',
    'Serbian (Latin Script)',
    'Slovene',
    'Slovak',
    'Ukrainian',
    'Lithuanian',
    'Latvian',
    'Macedonian',
    'Albanian',
    'Basque',
    'Catalan',
    'Welsh',
    'Luxembourgish',
    'Armenian',
    'Hebrew',
    'Arabic',
    'Farsi/Persian',
    'Turkish',
    'Kurdish',
    'Kyrgyz',
    'Turkmen',
    'Uyghur',
    'Mongolian',
  ];

  const eastAsianLanguages = [
    'Chinese',
    'Chinese (Simplified)',
    'Chinese (Traditional)',
    'Japanese',
    'Korean',
    'Vietnamese',
  ];

  if (europeanLanguages.includes(language)) return 'European';
  if (eastAsianLanguages.includes(language)) return 'East Asian';

  return 'Other';
}

export function hasHundredPlusBooks(language: string): boolean {
  const languagesWithRichLibraries = [
    'Assamese',
    'Bahasa Indonesia',
    'Bengali',
    'Chinese (Simplified)',
    'Chinese (Traditional)',
    'English',
    'Filipino',
    'French',
    'German',
    'Gondi',
    'Gujarati',
    'Haryanvi',
    'Hindi',
    'Igbo',
    'Italian',
    'Kannada',
    'Kiswahili',
    'Konkani',
    'Korean',
    'Korku',
    'Luganda',
    'Lusoga',
    'Malayalam',
    'Marathi',
    'Odia',
    'Portuguese',
    'Punjabi',
    'Sanskrit',
    'Serbian (Latin Script)',
    'Spanish',
    'Surjapuri',
    'Tamil',
    'Telugu',
    'Thai',
    'Tibetan',
    'Turkish',
    'Urdu',
    'Vietnamese',
  ];
  return languagesWithRichLibraries.includes(language);
}

export function getTotalLanguagesCount(): number {
  return STORYWEAVER_LANGUAGES_LIST.length;
}

export function getTotalIndianLanguagesCount(): number {
  return STORYWEAVER_LANGUAGES_LIST.filter((lang) => isIndianLanguage(lang)).length;
}

export function getLanguagesByRegion(region: string): string[] {
  return STORYWEAVER_LANGUAGES_LIST.filter(
    (lang) => getLanguageRegion(lang) === region
  );
}

export const STORYWEAVER_LEVELS = [
  'Level 1: Foundations',
  'Level 2: Early Reader',
  'Level 3: Intermediate',
  'Level 4: Advanced Reader',
];

export const READING_LEVEL_INFO: Record<
  string,
  { description: string; ageRange: string }
> = {
  'Level 1: Foundations': {
    description: 'For beginning readers learning letters and sounds',
    ageRange: 'Ages 3-4',
  },
  'Level 2: Early Reader': {
    description: 'For early readers with emerging decoding skills',
    ageRange: 'Ages 5-6',
  },
  'Level 3: Intermediate': {
    description: 'For readers gaining confidence and fluency',
    ageRange: 'Ages 7-8',
  },
  'Level 4: Advanced Reader': {
    description: 'For advanced readers with strong comprehension',
    ageRange: 'Ages 9+',
  },
};

export const STORYWEAVER_CATEGORIES = [
  'Animal Stories',
  'History and Culture',
  'Adventure and Mystery',
  'Bilingual',
  'Family and Friends',
  'Scary',
  'Fantasy',
  'Silly',
  'Science',
  'STEM',
  'Read-Aloud',
  'Early Readers',
];

export const LANGUAGES_WITH_100_PLUS_BOOKS = [
  'Assamese',
  'Bahasa Indonesia',
  'Bengali',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'English',
  'Filipino',
  'French',
  'German',
  'Gondi',
  'Gujarati',
  'Haryanvi',
  'Hindi',
  'Igbo',
  'Italian',
  'Kannada',
  'Kiswahili',
  'Konkani',
  'Korean',
  'Korku',
  'Luganda',
  'Lusoga',
  'Malayalam',
  'Marathi',
  'Odia',
  'Portuguese',
  'Punjabi',
  'Sanskrit',
  'Serbian (Latin Script)',
  'Spanish',
  'Surjapuri',
  'Tamil',
  'Telugu',
  'Thai',
  'Tibetan',
  'Turkish',
  'Urdu',
  'Vietnamese',
];
