export const STORYWEAVER_LANGUAGES = {
  // Indian Languages (Most Common)
  'Hindi': 'हिंदी',
  'Bengali': 'বাংলা',
  'Tamil': 'தமிழ்',
  'Telugu': 'తెలుగు',
  'Kannada': 'ಕನ್ನಡ',
  'Malayalam': 'മലയാളം',
  'Marathi': 'मराठी',
  'Gujarati': 'ગુજરાતી',
  'Punjabi': 'ਪੰਜਾਬੀ',
  'Urdu': 'اردو',
  'Assamese': 'অসমীয়া',
  'Odiya': 'ଓଡ଼ିଆ',
  'Konkani': 'कोंकणी',
  'Nepali': 'नेपाली',
  'Manipuri': 'মৈতৈলোল',
  'Santali': 'ᱥᱟᱱᱛᱟᱲᱤ',
  'Khasi': 'Khasi',
  'Sindhi': 'سنڌي',
  'Kashmiri': 'کأشُر',
  'Maithili': 'मैथिली',
  'Bhojpuri': 'भोजपुरी',
  'Sanskrit': 'संस्कृतम्',

    // International Languages
  'English': 'English',
  'Spanish': 'Español',
  'French': 'Français',
  'German': 'Deutsch',
  'Portuguese': 'Português',
  'Italian': 'Italiano',
  'Russian': 'Русский',
  'Chinese (Simplified)': '中文(简体)',
  'Chinese (Traditional)': '中文(繁體)',
  'Japanese': '日本語',
  'Korean': '한국어',
  'Arabic': 'العربية',
  'Turkish': 'Türkçe',
  'Polish': 'Polski',
  'Dutch': 'Nederlands',
  'Greek': 'Ελληνικά',
  'Swedish': 'Svenska',
  'Norwegian': 'Norsk',
  'Danish': 'Dansk',
  'Finnish': 'Suomi',
  'Czech': 'Čeština',
  'Hungarian': 'Magyar',
  'Romanian': 'Română',
  'Bulgarian': 'Български',
  'Croatian': 'Hrvatski',
  'Serbian': 'Српски',
  'Ukrainian': 'Українська',
  'Hebrew': 'עברית',
  'Vietnamese': 'Tiếng Việt',
  'Thai': 'ไทย',
  'Indonesian': 'Bahasa Indonesia',
  'Malay': 'Bahasa Melayu',
  'Filipino': 'Filipino',
  'Swahili': 'Kiswahili',
  'Amharic': 'አማርኛ',
  'Somali': 'Soomaali',
  'Yoruba': 'Yorùbá',
  'Igbo': 'Igbo',
  'Zulu': 'isiZulu',
  'Xhosa': 'isiXhosa',
  'Afrikaans': 'Afrikaans',
  'Hausa': 'Hausa',
  'Pidgin': 'Pidgin',
  'Lao': 'ລາວ',
  'Khmer': 'ខ្មែរ',
  'Mongolian': 'Монгол',
  'Tibetan': 'བོད་ཡིག',
};

export const STORYWEAVER_LANGUAGES_LIST = [
  // Indian Languages First
  'Hindi',
  'Bengali',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Marathi',
  'Gujarati',
  'Punjabi',
  'Urdu',
  'Assamese',
  'Odiya',
  'Konkani',
  'Nepali',
  'Manipuri',
  'Santali',
  'Khasi',
  'Sindhi',
  'Kashmiri',
  'Maithili',
  'Bhojpuri',
  'Sanskrit',

  // Then International
  'English',
  'Spanish',
  'French',
  'German',
  'Portuguese',
  'Italian',
  'Russian',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Japanese',
  'Korean',
  'Arabic',
  'Turkish',
  'Polish',
  'Dutch',
  'Greek',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Czech',
  'Hungarian',
  'Romanian',
  'Bulgarian',
  'Croatian',
  'Serbian',
  'Ukrainian',
  'Hebrew',
  'Vietnamese',
  'Thai',
  'Indonesian',
  'Malay',
  'Filipino',
  'Swahili',
  'Amharic',
  'Somali',
  'Yoruba',
  'Igbo',
  'Zulu',
  'Xhosa',
  'Afrikaans',
  'Hausa',
  'Pidgin',
  'Lao',
  'Khmer',
  'Mongolian',
  'Tibetan',
];

export function mapLanguageToStoryWeaver(language: string): string | null {
  const normalized = language.toLowerCase().trim();

  const languageMap: Record<string, string> = {
    'hindi': 'Hindi',
    'bengali': 'Bengali',
    'tamil': 'Tamil',
    'telugu': 'Telugu',
    'kannada': 'Kannada',
    'malayalam': 'Malayalam',
    'marathi': 'Marathi',
    'gujarati': 'Gujarati',
    'punjabi': 'Punjabi',
    'urdu': 'Urdu',
    'assamese': 'Assamese',
    'assami': 'Assamese',
    'odiya': 'Odiya',
    'oriya': 'Odiya',
    'konkani': 'Konkani',
    'nepali': 'Nepali',
    'manipuri': 'Manipuri',
    'meitei': 'Manipuri',
    'santali': 'Santali',
    'santal': 'Santali',
    'khasi': 'Khasi',
    'sindhi': 'Sindhi',
    'kashmiri': 'Kashmiri',
    'maithili': 'Maithili',
    'bhojpuri': 'Bhojpuri',
    'sanskrit': 'Sanskrit',

    'english': 'English',
    'spanish': 'Spanish',
    'español': 'Spanish',
    'french': 'French',
    'français': 'French',
    'german': 'German',
    'deutsch': 'German',
    'portuguese': 'Portuguese',
    'português': 'Portuguese',
    'italian': 'Italian',
    'italiano': 'Italian',
    'russian': 'Russian',
    'русский': 'Russian',
    'chinese': 'Chinese (Simplified)',
    '中文': 'Chinese (Simplified)',
    'japanese': 'Japanese',
    '日本語': 'Japanese',
    'korean': 'Korean',
    '한국어': 'Korean',
    'arabic': 'Arabic',
    'العربية': 'Arabic',
    'turkish': 'Turkish',
    'türkçe': 'Turkish',
    'polish': 'Polish',
    'polski': 'Polish',
    'dutch': 'Dutch',
    'nederlands': 'Dutch',
    'greek': 'Greek',
    'ελληνικά': 'Greek',
    'swedish': 'Swedish',
    'svenska': 'Swedish',
    'norwegian': 'Norwegian',
    'norsk': 'Norwegian',
    'danish': 'Danish',
    'dansk': 'Danish',
    'finnish': 'Finnish',
    'suomi': 'Finnish',
    'czech': 'Czech',
    'čeština': 'Czech',
    'hungarian': 'Hungarian',
    'magyar': 'Hungarian',
    'romanian': 'Romanian',
    'română': 'Romanian',
    'bulgarian': 'Bulgarian',
    'български': 'Bulgarian',
    'croatian': 'Croatian',
    'hrvatski': 'Croatian',
    'serbian': 'Serbian',
    'српски': 'Serbian',
    'ukrainian': 'Ukrainian',
    'українська': 'Ukrainian',
    'hebrew': 'Hebrew',
    'עברית': 'Hebrew',
    'vietnamese': 'Vietnamese',
    'tiếng việt': 'Vietnamese',
    'thai': 'Thai',
    'ไทย': 'Thai',
    'indonesian': 'Indonesian',
    'bahasa indonesia': 'Indonesian',
    'malay': 'Malay',
    'bahasa melayu': 'Malay',
    'filipino': 'Filipino',
    'tagalog': 'Filipino',
    'swahili': 'Swahili',
    'kiswahili': 'Swahili',
    'amharic': 'Amharic',
    'አማርኛ': 'Amharic',
    'somali': 'Somali',
    'soomaali': 'Somali',
    'yoruba': 'Yoruba',
    'yorùbá': 'Yoruba',
    'igbo': 'Igbo',
    'zulu': 'Zulu',
    'isizulu': 'Zulu',
    'xhosa': 'Xhosa',
    'isixhosa': 'Xhosa',
    'afrikaans': 'Afrikaans',
    'hausa': 'Hausa',
    'pidgin': 'Pidgin',
    'lao': 'Lao',
    'ລາວ': 'Lao',
    'khmer': 'Khmer',
    'ខ្មែរ': 'Khmer',
    'mongolian': 'Mongolian',
    'монгол': 'Mongolian',
    'tibetan': 'Tibetan',
    'བོད་ཡིག': 'Tibetan',
  };
  if (languageMap[normalized]) {
    return languageMap[normalized];
  }
  for (const [key, value] of Object.entries(languageMap)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return value;
    }
  }
  return language;
}

export function getLanguageNativeName(language: string): string {
  return STORYWEAVER_LANGUAGES[language as keyof typeof STORYWEAVER_LANGUAGES] || language;
}

export function isIndianLanguage(language: string): boolean {
  const indianLanguages = [
    'Hindi',
    'Bengali',
    'Tamil',
    'Telugu',
    'Kannada',
    'Malayalam',
    'Marathi',
    'Gujarati',
    'Punjabi',
    'Urdu',
    'Assamese',
    'Odiya',
    'Konkani',
    'Nepali',
    'Manipuri',
    'Santali',
    'Khasi',
    'Sindhi',
    'Kashmiri',
    'Maithili',
    'Bhojpuri',
    'Sanskrit',
  ];
  return indianLanguages.includes(language);
}


export const STORYWEAVER_LEVELS = [
  'Level 1: Foundations',
  'Level 2: Early Reader',
  'Level 3: Intermediate',
  'Level 4: Advanced Reader',
];

export const READING_LEVEL_INFO: Record<string, { description: string; ageRange: string }> = {
  'Level 1: Foundations': {
    description: 'For beginning readers learning letters and sounds',
    ageRange: 'Ages 3-4',
  },
  'Level 2: Early Reader': {
    description: 'For early readers with emerging decoding skills',
    ageRange: 'Ages 5-6',
  },
  'Level 3: Intermediate': {
    description: 'For readers gaining confidence and fluency',
    ageRange: 'Ages 7-8',
  },
  'Level 4: Advanced Reader': {
    description: 'For advanced readers with strong comprehension',
    ageRange: 'Ages 9+',
  },
};